export const PRODUCTS_LIST = [
    {
      name: "Elegant Bed Frame",
      tagline: "Luxury for Your Sleep",
      price: 799.99,
      type: "new",
    },
    {
      name: "Cozy Nightstand",
      tagline: "Compact and Stylish",
      price: 149.99,
      type: "sale",
      discountedPrice: 119.99,
    },
    {
      name: "Modern Sofa Set",
      tagline: "Comfort Redefined",
      price: 1299.99,
      // type: "new",
    },
    {
      name: "Coffee Table Ensemble",
      tagline: "Chic Living Room Addition",
      price: 299.99,
      // type: "new",
    },
    {
      name: "Dining Table Set",
      tagline: "Gather Around in Style",
      price: 899.99,
      type: "sale",
      discountedPrice: 799.99,
    },
    {
      name: "Wardrobe Organizer",
      tagline: "Maximize Bedroom Space",
      price: 599.99,
      type: "new",
    },
    {
      name: "Leather Recliner",
      tagline: "Relaxation Elevated",
      price: 699.99,
      type: "sale",
      discountedPrice: 599.99,
    },
    {
      name: "Contemporary Dining Chairs",
      tagline: "Elegance for Every Meal",
      price: 199.99,
      type: "new",
    },
    {
      name: "Bookshelf Tower",
      tagline: "Organize Your Living Space",
      price: 349.99,
      type: "new",
    },
    {
      name: "King Size Mattress",
      tagline: "Sleep Like Royalty",
      price: 899.99,
      type: "sale",
      discountedPrice: 799.99,
    },
  ];